# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

convert2logCpp <- function(titers) {
    .Call('_AbLandscapes_convert2logCpp', PACKAGE = 'AbLandscapes', titers)
}

#' Calculate log likelihood of single fitted HI titer
#' 
#' This is the base function for performing a maximum likelihood calculation for a 
#' single fitted HI titer given upper and lower limits of the measured value.
#'
#' @param max_titer The upper bound of the measured titer.
#' @param min_titer The lower bound of the measured titer.
#' @param pred_titer The predicted titer.
#' @param error_sd The standard deviation of the error.
#'
#' @details This function simply calculates to log likelihood of a predicted measurement 
#' given the upper and lower bounds of the measurement, the main assumption being that the 
#' associated error is normally distributed.
#'
#' @return Returns the log-likelihood of the measured titer given the measured titer 
#' bounds and error standard deviation supplied.
#' @export
calc_titer_loglik <- function(max_titer, min_titer, pred_titer, error_sd) {
    .Call('_AbLandscapes_calc_titer_loglik', PACKAGE = 'AbLandscapes', max_titer, min_titer, pred_titer, error_sd)
}

#' Calculate the total negative log-likelihood of a predicted titer set
#' 
#' This is a base function to sum the total _negative_ log likelihood of a predicted 
#' and measured set of HI titers.
#' 
#' @param max_titers Numeric vector of the upper bounds of the measured titers.
#' @param min_titers Numeric vector of the lower bounds of the measured titers.
#' @param pred_titers Numeric vector of predicted titers.
#' @param titer_weights Numeric vector of titer weights.
#' @param hi_error_sd The standard deviation of the error.
#' 
#' @details This function simply calculates to log likelihood of a series of predicted 
#' measurements given the upper and lower bounds of the measurements, the main assumption 
#' being that the associated error is normally distributed.
#' @export
calc_titer_set_negll <- function(max_titers, min_titers, pred_titers, titer_weights, hi_error_sd) {
    .Call('_AbLandscapes_calc_titer_set_negll', PACKAGE = 'AbLandscapes', max_titers, min_titers, pred_titers, titer_weights, hi_error_sd)
}

#' Calculate the total negative log-likelihood of a mean titer
#' 
#' This is a base function to sum the total _negative_ log likelihood of a mean titer.
#' 
#' @param max_titers Numeric vector of the upper bounds of the measured titers.
#' @param min_titers Numeric vector of the lower bounds of the measured titers.
#' @param predicted_mean The predicted mean titer.
#' @param titer_sd The expected standard deviation of titers.
#' 
#' @details This function calculates the total negative log-likelihood of a predicted mean 
#' titer given a set of titers. The main assumption is that both measurement error and 
#' titer variation are normally distributed. Note that the argument \code{titer_sd} is the 
#' total expected standard deviation of the titer set, i.e. measurement error plus titer 
#' variation.
#' 
calc_mean_titer_negll <- function(predicted_mean, max_titers, min_titers, titer_sd) {
    .Call('_AbLandscapes_calc_mean_titer_negll', PACKAGE = 'AbLandscapes', predicted_mean, max_titers, min_titers, titer_sd)
}

#' Calculate the total negative log-likelihood of a mean titer where the standard deviation 
#' is unknown. This is an internal function used by the function mean_titer.
#' 
calc_mean_titer_negll_without_sd <- function(pars, max_titers, min_titers) {
    .Call('_AbLandscapes_calc_mean_titer_negll_without_sd', PACKAGE = 'AbLandscapes', pars, max_titers, min_titers)
}

#' @export
get_lndscp_fit_negll <- function(max_titre, min_titre, pred_titre, error_sd) {
    .Call('_AbLandscapes_get_lndscp_fit_negll', PACKAGE = 'AbLandscapes', max_titre, min_titre, pred_titre, error_sd)
}

#' @export
get_lndscp_prediction_set_negll <- function(min_titres, max_titres, pred_titres, error_sd) {
    .Call('_AbLandscapes_get_lndscp_prediction_set_negll', PACKAGE = 'AbLandscapes', min_titres, max_titres, pred_titres, error_sd)
}

#' @export
get_negll_hi_lm <- function(par, max_titres, min_titres, ag_coords, ag_weights, error_sd) {
    .Call('_AbLandscapes_get_negll_hi_lm', PACKAGE = 'AbLandscapes', par, max_titres, min_titres, ag_coords, ag_weights, error_sd)
}

#' @export
get_negll_hi_height <- function(par, lndscp_height, max_titres, min_titres, ag_coords, ag_weights, error_sd) {
    .Call('_AbLandscapes_get_negll_hi_height', PACKAGE = 'AbLandscapes', par, lndscp_height, max_titres, min_titres, ag_coords, ag_weights, error_sd)
}

#' @export
get_negll_lm <- function(par, pred_titres, max_titres, min_titres, error_sd) {
    .Call('_AbLandscapes_get_negll_lm', PACKAGE = 'AbLandscapes', par, pred_titres, max_titres, min_titres, error_sd)
}

#' @export
get_negll_lm_intercept <- function(par, pred_titres, max_titres, min_titres, lm_gradient, error_sd) {
    .Call('_AbLandscapes_get_negll_lm_intercept', PACKAGE = 'AbLandscapes', par, pred_titres, max_titres, min_titres, lm_gradient, error_sd)
}

#' @export
get_negll_lm_gradient <- function(par, pred_titres, max_titres, min_titres, lm_intercept, error_sd) {
    .Call('_AbLandscapes_get_negll_lm_gradient', PACKAGE = 'AbLandscapes', par, pred_titres, max_titres, min_titres, lm_intercept, error_sd)
}

